Feature/uppsf 1565 migrate to structured logging
Financial-Times/public-concordances-api pull request #44
Opened 2021-04-07 10:07 UTC by ivanruski

## What
Migrate the api to structured logging

## Why

[UPPSF-1565](https://financialtimes.atlassian.net/browse/UPPSF-1565)

## Anything, in particular, you'd like to highlight to reviewers

_Is it okay that I've changed the messages for the 500 responses and the logs as well_

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-04-12 06:44 UTC, ivan-p-nikolov reviewed
Looks good. I just have some suggestions to make it better.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on concordances/handlers.go
>  	_, conceptIDExist := m["conceptId"]
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion(non-blocking):** We are reading `conceptId` and `authority` from `m` valies multiple times. The code would be cleaner if we just store them in variables here and reuse them down the line.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on concordances/handlers.go
> +func NewHTTPHandler(neoURL, cacheDuration, env string, batchSize int, log *logger.UPPLogger) (*HTTPHandler, error) {
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion(non-blocking):** The constructor returns an error. That means it could fail. It would be nice if we have a test that covers the fail states.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on concordances/handlers.go
> +	w.Header().Set("Cache-Control", hh.cacheControlHeader)
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion(non-blocking):** Can we add a test that we setup the correct `Cache-Control` header for the responses.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on concordances/handlers.go
> +	hh.log.Debugf("Concordance(uuid:%s): %s\n", Jason, Jason)
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion:** This log looks strange. We are logging the same thing twice. We should either remove it, or rework it to bring meaningful information.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on concordances/handlers.go
>  const (
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion(non-blocking):** I would move all concepts to the top of the file for readability.

2021-04-12 06:44 UTC, ivan-p-nikolov commented on main.go
>  	if err := http.ListenAndServe(":"+port, nil); err != nil {
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously. -->
**suggestion(non-blocking):** Can we add graseful shutdown to the service. Barebones example can be found [here](https://github.com/Financial-Times/cm-go-service/blob/c9314ea749d19ba241e0ff441160684053c7d323/main.go#L158)

2021-04-12 08:12 UTC, mchompalova requested changes

2021-04-12 08:29 UTC, ivanruski commented on concordances/handlers.go
>  	_, conceptIDExist := m["conceptId"]
I will fix this in the next PR

2021-04-12 08:31 UTC, ivanruski commented on concordances/handlers.go
> +func NewHTTPHandler(neoURL, cacheDuration, env string, batchSize int, log *logger.UPPLogger) (*HTTPHandler, error) {
I've updated the conctructor to return only *HTTPHandler, I will add the tests in the next PR

2021-04-12 08:32 UTC, ivanruski commented on concordances/handlers.go
> +	hh.log.Debugf("Concordance(uuid:%s): %s\n", Jason, Jason)
I've removed it

2021-04-12 08:35 UTC, ivanruski commented on concordances/handlers.go
>  const (
done

2021-04-12 10:24 UTC, ivanruski commented on concordances/handlers.go
> +	w.Header().Set("Cache-Control", hh.cacheControlHeader)
I will put this in the next PR as well, since it's not related to the logging functionallity

2021-04-12 10:31 UTC, ivanruski commented on main.go
>  	if err := http.ListenAndServe(":"+port, nil); err != nil {
I will add graseful shutdown in the next PR.

2021-04-12 10:34 UTC, ivanruski commented on concordances/cypher.go
> +		return Concordances{}, false, fmt.Errorf("concordances.ReadByConceptID: error accessing Concordance datastore for identifier %v: %w", identifiers, err)
done

2021-04-12 10:36 UTC, ivanruski commented on concordances/cypher_test.go
> +	// Used in concepts-rw-neo4j
I've removed the whole init function

2021-04-12 10:59 UTC, ivanruski commented on concordances/handlers.go
> +var (
I will do this in the next PR since it's not related to the task

2021-04-12 11:20 UTC, ivanruski commented on concordances/handlers.go
> +		w.Write([]byte(`{"message": "error accessing Concordance datastore"}`))
If I leave the original message we will be writing wrapped error to the response. This might not be okay since the inner error (will be non-nill if something goes wrong when connectiong to neo4j) will expose information about the internals of the api.

2021-04-12 11:21 UTC, ivanruski commented on concordances/handlers.go
> +			Timeout: 1 * time.Minute,
I will fix this in the next PR, I am planning to move this code in the constructor function in cypher.go.

2021-04-12 12:06 UTC, ivanruski commented on concordances/handlers.go
> +			hh.Log.WithError(err).WithTransactionID(tid).
done

2021-04-12 12:06 UTC, ivanruski commented on concordances/handlers.go
> +		transactionID := transactionidutils.GetTransactionIDFromRequest(r)
done

2021-04-12 12:06 UTC, ivanruski commented on concordances/handlers.go
> +	Log *logger.UPPLogger
done

2021-04-12 12:54 UTC, ivan-p-nikolov reviewed
> Is it okay that I've changed the messages for the 500 responses and the logs as well

I see no problem with it.

2021-04-12 12:54 UTC, ivan-p-nikolov commented on concordances/handlers.go
> +	hh.log.Debugf("Concordance request: %s", r.URL.RawQuery)
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**suggestion:** ‏Move this line after creating `logEntry` and use the object to create this log. That way the new log entry will also have `transaction_id` field.

2021-04-12 12:54 UTC, ivan-p-nikolov commented on main.go
>  	_ "github.com/joho/godotenv/autoload"
<!-- Chores are simple tasks that must be done before the subject can be “officially” accepted. Usually, these comments reference some common process. Try to leave a link to the process description so that the reader knows how to resolve the chore.  -->
**chore:** ‏For the next PR. I'm not convinced that we use this `autoload` lib. Can you check ? And if we don't can we remove it?

2021-04-13 07:30 UTC, ivanruski commented on concordances/handlers.go
> +	hh.log.Debugf("Concordance request: %s", r.URL.RawQuery)
done

2021-04-13 07:37 UTC, ivan-p-nikolov approved these changes

2021-04-13 10:35 UTC, mchompalova approved these changes

2021-04-14 08:12 UTC, merged