Fix/uppsf 2297 refactoring
Financial-Times/public-concordances-api pull request #46
Opened 2021-04-14 11:57 UTC by ivanruski

# Description

## What

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code

## Why

Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-04-15 05:55 UTC, ivan-p-nikolov submitted a review, later dismissed
My major concerns for the global variables and the graceful shutdown have been addressed, so I'm happy camper.
There are more things that could be fixed, but that's OK for now.

2021-04-15 05:55 UTC, ivan-p-nikolov commented on concordances/handlers_test.go
>  func init() {
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**nitpick (non-blocking):** It works, but I don't think that using the `init` function ‏for test setup is a great idea. I would define explicit `setup` and `teardown` functions and use them in any test that needs them. Or use `testify` [test suit functionality](https://pkg.go.dev/github.com/stretchr/testify/suite).

2021-04-15 05:55 UTC, ivan-p-nikolov commented on concordances/handlers.go
> -func StartAsyncChecker(checkInterval time.Duration) {
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought:** ‏Is there a way to check whether there will be significant impact when we remove this cached health check?

2021-04-15 05:55 UTC, ivan-p-nikolov commented on main.go
> +func parseCacheDurationArg(cacheDuration string) (string, error) {
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**suggestion (non-blocking):** There could be a test to check that we create the header string in the correct format. ‏

2021-04-19 06:17 UTC, mchompalova requested changes
Looks good, only a few minor comments.
Also, I would remove "remove unused imports" from the second commit message :)

2021-04-19 06:17 UTC, mchompalova commented on main.go
>  	// The top one of these feels more correct, but the lower one matches what we have in Dropwizard,
I don't quite understand this comment.

2021-04-19 06:17 UTC, mchompalova commented on main.go
> +		go startHTTPServer(srv, log)
**question** Starting the server was synchronous, why do we want to make it asynchronous?

2021-04-19 06:17 UTC, mchompalova commented on main.go
> +	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
**suggestion** Can we add a log line here saying that the server is starting?

2021-04-19 06:17 UTC, mchompalova commented on main.go
> +			log.WithError(err).Fatalf("Appliaction failed to start")
Can we fix the typo?

2021-04-19 09:55 UTC, ivanruski commented on concordances/handlers.go
> -func StartAsyncChecker(checkInterval time.Duration) {
I've tried hitting the `__health` endpoints on both `dev` and `staging` and the results are similar. There wasn't any significant difference between the response time of the requests.

Also I've checked several other apis to see how the healthcheck is implemented and all of them were checking the connectivity similarly.

2021-04-19 10:31 UTC, ivanruski commented on main.go
> +func parseCacheDurationArg(cacheDuration string) (string, error) {
[TestCorrectCacheControlHeadersAreSet](https://github.com/Financial-Times/public-concordances-api/pull/46/files#diff-eb18c7d99b12fda2428dce1f55b217e90670167d3f810ccf8223298dcd756d14R140) should catch that as well.

2021-04-19 10:38 UTC, ivanruski commented on concordances/handlers.go
>  		Timeout: 10 * time.Second,
What do you mean by "move this to a variable" ?
Something like this: 
```
healthCheck := fthealth.TimedHealthCheck{
        HealthCheck: fthealth.HealthCheck{
	        SystemCode:  serviceName,
	        Name:        serviceName,
	        Description: "Concords concept identifiers",
	        Checks: []fthealth.Check{
		        {
			        BusinessImpact:   "Unable to respond to Public Concordances API requests",
			        Name:             "Check connectivity to Neo4j",
			        PanicGuide:       "https://runbooks.ftops.tech/public-concordances-api",
			        Severity:         1,
			        TechnicalSummary: "Cannot connect to Neo4j a instance with at least one concordance loaded in it",
			        Checker:          hh.databaseConnectivityChecker,
		        },
	        },
        },
        Timeout: 10 * time.Second,
}

return healthCheck
```

2021-04-19 10:48 UTC, ivanruski commented on main.go
>  	// The top one of these feels more correct, but the lower one matches what we have in Dropwizard,
I am not sure either. I guess the comment is here because this service has `_build-info` and `build-info` endpoints with the same handler.

2021-04-19 10:55 UTC, ivanruski commented on main.go
> +		go startHTTPServer(srv, log)
I was following the style guide in https://github.com/Financial-Times/cm-go-service while I was adding the graceful shutdown to the service. And since `startHTTPServer` is a blocking function we execute it in a separate goroutine and wait for a stop signal in the main goroutine.

2021-04-19 10:57 UTC, ivanruski commented on main.go
> +			log.WithError(err).Fatalf("Appliaction failed to start")
done

2021-04-19 10:57 UTC, ivanruski commented on main.go
> +	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
done

2021-04-19 10:57 UTC, ivanruski commented on main.go
> +				Timeout: 1 * time.Minute,
done

2021-04-19 11:00 UTC, mchompalova commented on concordances/handlers.go
>  		Timeout: 10 * time.Second,
Only the timeout value :)

2021-04-19 11:01 UTC, mchompalova commented on main.go
> +		go startHTTPServer(srv, log)
Thanks for the clarification.

2021-04-19 11:11 UTC, ivanruski commented on concordances/handlers.go
>  		Timeout: 10 * time.Second,
done

2021-04-20 05:56 UTC, mchompalova commented on main.go
>  	// The top one of these feels more correct, but the lower one matches what we have in Dropwizard,
It's actually 2 comments. IMO it's safe to delete the first one :)

2021-04-20 06:10 UTC, mchompalova commented on concordances/handlers.go
>  		Timeout: 10 * time.Second,
My suggestion is to move the const at the top of the file and we can name it `healthCheckTimeout` to be more clear :)

2021-04-20 07:18 UTC, ivan-p-nikolov approved these changes

2021-04-20 07:18 UTC, mchompalova approved these changes

2021-04-20 10:05 UTC, merged