Feature/uppsf 2797 migrate to cm neo4j driver
Financial-Times/public-concordances-api pull request #48
Opened 2021-11-09 08:25 UTC by mchompalova

# Description

## What

We migrated the service to the new cm-neo4j-driver.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-2797

## Anything, in particular, you'd like to highlight to reviewers

Because this service depends on `concepts-rw-neo4j`, I've put a dependency to the RC. Once `concepts-rw-neo4j` is merged, I'll update it

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-11-10 18:39 UTC, ManoelMilchev commented on main.go
> +		"NEO_URL":        *neoURL,
nitpick(non-blocking): Can we also add the `port` here for better consistency with the other migrated services?
```suggestion
		"NEO_URL":        *neoURL,
		"PORT":        *port,
```

2021-11-10 18:39 UTC, ManoelMilchev commented on concordances/cypher_test.go
> +func getDatabaseConnection(assert *assert.Assertions) neoutils.NeoConnection {
Please confirm if i understand this part right here. We are creating a new Neo connection because in the tests we have to create concepts-rw service so we can place entries in the  database, after that we are trying to read them through the new cm-neo4j-driver. Is that correct ?

2021-11-11 12:27 UTC, epavlova requested changes

2021-11-11 12:27 UTC, epavlova commented on docker-compose-tests.yml
> +      - NEO4J_TEST_URL=bolt://neo4j:7687
**issue:** The integration tests are not passing. This service uses new and old driver it its integration tests which means two different protocols. Here we kept single connection string to the db which can't satisfy both drivers.
You can check how the same thing is implemented in:
 https://github.com/Financial-Times/concept-exporter or https://github.com/Financial-Times/public-content-by-concept-api

2021-11-11 12:27 UTC, epavlova commented on concordances/cypher_test.go
> +	"testing"
**suggestion:** Those tests are actually integration tests and if we run them they are doing modifications to the db. It's safer to add [build tag](https://github.com/Financial-Times/public-content-by-concept-api/blob/master/content/service_test.go#L1). That way if we are connected to a real db and by chance type `go test` we won't affect the db because the tests won't be run.

2021-11-17 08:03 UTC, ManoelMilchev approved these changes
LGTM

2021-11-17 08:17 UTC, epavlova requested changes
I just noticed one more issue, I missed it on the first review.

2021-11-17 08:17 UTC, epavlova commented on concordances/cypher.go
> +	if errors.Is(err, cmneo4j.ErrNoResultsFound) {
**issue:** This error check should be before the general error check on line `189`, because `if err != nil` will be true also for `cmneo4j.ErrNoResultsFound` and the execution in case of error will always be handled from line `190`.

2021-11-18 07:41 UTC, ManoelMilchev approved these changes
LGTM

2021-11-18 08:06 UTC, epavlova approved these changes

2021-11-18 08:06 UTC, merged